server:
  port: 8087

spring:
  datasource:
    url: ${AUTH_DATABASE_URL}
    username: ${AUTH_DATABASE_USER}
    password: ${AUTH_DATABASE_PASSWORD}
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
        show_sql: true
  jackson:
    default-property-inclusion: non_null

course:
  url: http://localhost:8082
