spring:
  application:
    name: ead-auth-user-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
      username: ${CONFIG_SERVER_USERNAME}
      password: ${CONFIG_SERVER_PASSWORD}
