server:
  port: 8084

spring:
  application:
    name: ead-notification-service
  datasource:
    url: ${NOTIFICATION_DATABASE_URL}
    username: ${NOTIFICATION_DATABASE_USER}
    password: ${NOTIFICATION_DATABASE_PASSWORD}
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
        show_sql: true
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
