server:
  port: 8087

spring:
  application:
    name: ead-auth-user-service
  datasource:
    url: ${AUTH_DATABASE_URL}
    username: ${AUTH_DATABASE_USER}
    password: ${AUTH_DATABASE_PASSWORD}
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
        show_sql: true
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    hostname: localhost
