server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URI}
          default-label: ${GITHUB_BRANCH}
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
