server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_URI}
          default-label: ${GITHUB_BRANCH}
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_PASSWORD}

ead:
  config-server:
    username: ${CONFIG_SERVER_USERNAME:configserver}
    password: ${CONFIG_SERVER_PASSWORD:ead123cs}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
