ead:
  service-registry:
    username: serviceRegistry
    password: ead123sr
  auth:
    jwt:
      secret: ${JWT_SECRET}
      expiresIn: ${JWT_EXPIRES_IN}

eureka:
  client:
    service-url:
      defaultZone: 'https://${ead.service-registry.username}:${ead.service-registry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost
