server:
  port: 8082

spring:
  datasource:
    url: ${COURSE_DATABASE_URL}
    username: ${COURSE_DATABASE_USER}
    password: ${COURSE_DATABASE_PASSWORD}
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
        show_sql: true
  rabbitmq:
    host: localhost
    username: rabbitmq
    password: rabbitmq

ead:
  broker:
    exchange:
      userEvent: ead.userevent
      notificationCommandExchange: ead.notificationCommand
    queue:
      userEventQueue:
        name: ead.userevent.ms.course
    key:
      notificationCommandKey: ms.notification
